allow_net = [
  "www.marketwatch.com",
  "feeds.finance.yahoo.com",
  "seekingalpha.com",
  "www.fool.com",
  "www.benzinga.com",
  "www.coindesk.com",
  "cointelegraph.com",
  "cryptoslate.com",
  "decrypt.co",
  "www.theblockcrypto.com",
  "feeds.reuters.com",
  "feeds.bloomberg.com",
  "www.ft.com",
  "feeds.a.dj.com",
  "www.cnbc.com",
  "www.earningswhispers.com",
  "www.zacks.com",
  "www.streetinsider.com",
  "www.thestreet.com",
  "www.investors.com",
  "feeds.bbci.co.uk",
  "feeds.apnews.com",
  "www.foreignaffairs.com",
  "www.politico.com"
]